### ISSUE TITLE
Possibly invalid static import

### ISSUE THREAD

**Issue by kyberorg** [codeborne/play-tests#5]
At README there is static import:
`import static com.codeborne.Selenide.*;`

when I tried this import method `open("/");` - remains unresolved.

shouldn't it be
`import static com.codeborne.selenide.Selenide.*;`
instead ?

**Comment by asolntsev** [comment]
@kyberorg You are right, the right import should be:
`import static com.codeborne.selenide.Selenide.*`

**Comment by asolntsev** [comment]
fixed import
